### ISSUE TITLE
Entorno de trabajo en mac: gophernotes y jupyter con python3

### ISSUE THREAD

**Issue by fjlopez** [hashcodezgz/hashcodezgz.github.io#2]
Probar en un equipo mac la instalación de gophernotes y jupyter y crea un hola mundo.

**Comment by fjlopez** [comment]
En OSX la mejor solución es instalar el gesto de paquetes [Anaconda 3.6](https://repo.continuum.io/archive/Anaconda3-5.0.1-MacOSX-x86_64.pkg). Las pruebas con `brew` han dado problemas posiblemente por problemas en la configuración del equipo.

**Comment by fjlopez** [comment]
La solución más rápida para OSX es instalar via Docker la versión para go
```
docker run -it -p 8888:8888 gopherdata/gophernotes-ds
```
pero no tiene mapeado un volumen para conectar con el host.

**Comment by lAngelP** [comment]
Para Windows recomiendan también esa opción, pero yo lo he hecho sin Docker.
